label: Fuzzy Interval (Refined Contour) Single Features
description: "Histogram counts, mode, entropy and Zipf coefficient of distribution of all 9 fuzzy interval classes (FUZZYINT). Values: **big jump up/down** (+/-4), **jump** up/down** (+/-3), **leap up/down** (+/-1), **step up/down** (+/-1), **repetition** (0)"
category: Interval

feature:

  source:
    FUZZYINT:
      param: fuzzyinterval
      
  process:

    HIST:
      type: hist
      histogramType: ordinal
      min: -4
      max: +4
      density: True
      inputVec: FUZZYINT.outputVec

    MODE:
      type: stat
      measure: mode
      inputVec: FUZZYINT.outputVec           

    ZIPF:
      type: stat
      measure: zipf_coefficient
      inputVec: FUZZYINT.outputVec           

    ENTROPY:
      type: stat
      measure: entropy
      numberClasses: 11
      inputVec: FUZZYINT.outputVec           
       
  sink:

    F0:
      type: sink
      input: HIST.histVec
      index: 0
      label: fuzzyint_hist_09_big_jump_down
      doc:
        type: Real
        length: 1
        description: "Relative frequency **big jump down** (-4)"
    F1:
      type: sink
      input: HIST.histVec
      index: 1
      label: fuzzyint_hist_08_jump_down
      doc:
        type: Real
        length: 1
        description: "Relative frequency **jump down** (-3)"
    F2:
      type: sink
      input: HIST.histVec
      index: 2
      label: fuzzyint_hist_07_leap_down
      doc:
        type: Real
        length: 1
        description: "Relative frequency **leap down** ( -2)"
    F3:
      type: sink
      input: HIST.histVec
      index: 3
      label: fuzzyint_hist_06_step_down
      doc:
        type: Real
        length: 1
        description: "Relative frequency **step down** (-1)"
    F4:
      type: sink
      input: HIST.histVec
      index: 4
      label: fuzzyint_hist_05_repeat
      doc:
        type: Real
        length: 1
        description: "Relative frequency **repetition** (0)"
    F5:
      type: sink
      input: HIST.histVec
      index: 5
      label: fuzzyint_hist_04_step_up
      doc:
        type: Real
        length: 1
        description: "Relative frequency **step up** (+1)"
    F6:
      type: sink
      input: HIST.histVec
      index: 6
      label: fuzzyint_hist_03_leap_up
      doc:
        type: Real
        length: 1
        description: "Relative frequency **leap up** (+2)"
    F7:
      type: sink
      input: HIST.histVec
      index: 7
      label: fuzzyint_hist_02_jump_up
      doc:
        type: Real
        length: 1
        description: "Relative frequency **jump up** (+3)"
    F8:
      type: sink
      input: HIST.histVec
      index: 8
      label: fuzzyint_hist_01_big_jump_up
      doc:
        type: Real
        length: 1
        description: "Relative frequency **big jump up** (+4)"

    F9:
      type: sink
      input: MODE.outputVec
      label: fuzzyint_mode
      doc:
        type: Real
        length: Var
        description: Mode of FUZZYINT distribution (can be list!)

    F10:
      type: sink
      input: ZIPF.outputVec
      label: fuzzyint_zipf
      doc:
        type: Real
        length: 1
        description: Zipf coefficient of FUZZYINT distribution 

    F11:
      type: sink
      input: ENTROPY.outputVec
      label: fuzzyint_entropy
      doc:
        type: Real
        length: 1
        description: Normalized entropy of FUZZYINT distribution 