label: Inter-onset Interval Class Distribution
description: 'Histogram and raw vector of IOI classes (**very short**: -2, **short**: -1, **medium**: 0, **long**: 1, **very long**: 2) as well as differences and sign of differences. 
Reference time-span is either local beat duration ("relative mode") or 0.5 sec ("absolute mode")'
category: Rhythm

feature:

  source:
    IOI_ABS:
      param: ioiclass
      optParam: abs

    IOI_REL:
      param: ioiclass
      optParam: rel
      
  process:

    HIST_ABS:
      type: hist
      histogramType: ordinal
      min: -2
      max: 2
      density: False
      inputVec: IOI_ABS.outputVec

    HIST_REL:
      type: hist
      histogramType: ordinal
      min: -2
      max: 2
      density: False
      inputVec: IOI_REL.outputVec

    DIFF_ABS:
      type: diff
      inputVec: IOI_ABS.outputVec       
    DIFF_REL:
      type: diff
      inputVec: IOI_REL.outputVec       

    DIFF_ABS_SIG:
      type: sign
      inputVec: DIFF_ABS.outputVec       
      
      
    DIFF_REL_SIG:
      type: sign
      inputVec: DIFF_REL.outputVec       

  sink:

    F1:
      type: sink
      input: IOI_ABS.outputVec
      label: ioiclass_abs_raw
      doc:
        type: Integer
        length: N
        description: Raw output of IOI classes of all melody notes (absolute mode) 

    F2:
      type: sink
      input: HIST_ABS.bins  
      label: ioiclass_abs_hist_values
      doc:
        type: Integer [-2:2]
        length: 5
        description: Histogram bin values (absolute mode)

    F3:
      type: sink
      input: HIST_ABS.histVec
      label: ioiclass_abs_hist_dens
      doc:
        type: Integer
        length: 5
        description: Histogram bin counts (absolute mode)

    F4:
      type: sink
      input: IOI_REL.outputVec
      label: ioiclass_rel_raw
      doc:
        type: Integer
        length: N
        description: Raw output of IOI classes of all melody notes (relative mode) 

    F5:
      type: sink
      input: HIST_REL.bins  
      label: ioiclass_rel_hist_values
      doc:
        type: Integer [-2:2]
        length: 5
        description: Histogram bin values  (relative mode)

    F6:
      type: sink
      input: HIST_REL.histVec
      label: ioiclass_rel_hist_counts
      doc:
        type: Integer
        length: 5
        description: Histogram bin counts (relative mode)
    F7:
      type: sink
      input: DIFF_ABS.outputVec
      label: ioiclass_abs_diff_raw
      doc:
        type: Integer
        length: N-1
        description: Raw output of differences of IOI classes of all melody notes (absolute mode) 
    F8:
      type: sink
      input: DIFF_REL.outputVec
      label: ioiclass_rel_diff_raw
      doc:
        type: Integer
        length: N-1
        description: Raw output of differences of IOI classes of all melody notes (relative mode) 
    F9:
      type: sink
      input: DIFF_ABS_SIG.outputVec
      label: ioiclass_abs_diff_sig_raw
      doc:
        type: Integer [-1:1]
        length: N-1
        description: Raw output of sig of differences of IOI classes of all melody notes (absolute mode) 
    F10:
      type: sink
      input: DIFF_REL.outputVec
      label: ioiclass_rel_diff_sig_raw
      doc:
        type: Integer [-1:1]
        length: N-1
        description: Raw output of sign of differences of IOI classes of all melody notes (relative mode) 
