label: Inter-onset Interval Class Bigrams
description: "Histogram features for rel. IOI classes (IOICLASS) bigrams: all unique IOICLASS bigrams and all IOICLASS bigrams occuring at least twice."
category: Sequence/Rhythm

feature:

  source:

    IOICLASS:
      param: ioiclass

  process:

    NGRAM:
      type: ngram
      N: 2
      inputVec: IOICLASS.outputVec

    NGRAMHIST:
      type: hist
      histogramType: nominal
      inputVec: NGRAM.outputVec

    TH1:
      type: threshold
      inputVec: NGRAMHIST.histVec
      threshold: 1
      operator: "gt"

    SEL1:
      type: selector
      inputVec: NGRAMHIST.bins
      selectVec: TH1.outputVec

    SEL2:
      type: selector
      inputVec: NGRAMHIST.histVec
      selectVec: TH1.outputVec

    ENTROPY:
      type: stat
      measure: entropy_hist
      normalizeEntropy: False
      inputVec: NGRAMHIST.histVec           

    ENTROPY_NORM:
      type: stat
      measure: entropy_hist
      normalizeEntropy: True
      numberClasses: 25
      inputVec: NGRAMHIST.histVec           

  sink:

    F1:
      type: sink
      input: NGRAMHIST.bins
      label: ioiclass_bigrams
      doc:
        type: String
        length: Var
        description: Histogram bins (all unique IOICLASS bigrams)

    F2:
      type: sink
      input: NGRAMHIST.histVec
      label: ioiclass_bigram_counts
      doc:
        type: Integer
        length: Var
        description: Histogram bin count (all unique IOICLASS bigrams)

    F3:
      type: sink
      input: SEL1.outputVec
      label: ioiclass_bigram_pattern
      doc:
        type: String
        length: Var
        description: Histogram bins (all unique IOICLASS bigrams occuring at least twice)

    F4:
      type: sink
      input: SEL2.outputVec
      label: ioiclass_bigram_pattern_count
      doc:
        type: Integer
        length: Var
        description: Histogram bin count (all unique IOICLASS bigrams occuring at least twice)

    F5:
      type: sink
      input: ENTROPY.outputVec
      label: ioiclass_bigram_entropy
      doc:
        type: Real
        length: 1
        description: Unnormalized Entropy of bigram distribution in bits
    F6:
      type: sink
      input: ENTROPY_NORM.outputVec
      label: ioiclass_bigram_entropy_norm
      doc:
        type: Real [0,1]
        length: 1
        description: Normalized Entropy of bigram distribution 