label: Average Run-lengths of Parsons Sequences
description: Run-lengths and means of sequences of all (Parson's) intervals directions
category: Sequence/Interval

feature:
  source:
    P:
      param: parsons

  process:
    # compute interval 

    # run-length
    RL: 
      type: runlength
      inputVec: P.outputVec

        
    # mask with True for segments with intervals of +1 or -1 semitones
    TH_ASC:
      type: threshold
      inputVec: RL.segVal
      threshold: 1
      operator: "eq"

    TH_DESC:
      type: threshold
      inputVec: RL.segVal
      threshold: -1
      operator: "eq"

    TH_REP:
      type: threshold
      inputVec: RL.segVal
      threshold: 0
      operator: "eq"

    SEL_ASC:
      type: selector
      inputVec: RL.segLen
      selectVec: TH_ASC.outputVec

    SEL_DESC:
      type: selector
      inputVec: RL.segLen
      selectVec: TH_DESC.outputVec

    SEL_REP:
      type: selector
      inputVec: RL.segLen
      selectVec: TH_REP.outputVec
    
    # find segments with at least 2 intervals
 
    TH_ASC_2:
      type: threshold
      inputVec: SEL_ASC.outputVec
      threshold: 2
      operator: "ge"

    SEL_LEN_ASC:
      type: selector
      inputVec: SEL_ASC.outputVec
      selectVec: TH_ASC_2.outputVec

    TH_DESC_2:
      type: threshold
      inputVec: SEL_DESC.outputVec
      threshold: 2
      operator: "ge"

    SEL_LEN_DESC:
      type: selector
      inputVec: SEL_DESC.outputVec
      selectVec: TH_DESC_2.outputVec
 
    TH_REP_2:
      type: threshold
      inputVec: SEL_REP.outputVec
      threshold: 2
      operator: "ge"

    SEL_LEN_REP:
      type: selector
      inputVec: SEL_REP.outputVec
      selectVec: TH_REP_2.outputVec
        
    # mean length of chromatic note sequences

    ARI_ASC: 
      type: arithmetic
      operator: "+"
      inputVec1: SEL_LEN_ASC.outputVec
      inputVec2: 1

    ARI_DESC: 
      type: arithmetic
      operator: "+"
      inputVec1: SEL_LEN_DESC.outputVec
      inputVec2: 1
      
    ARI_REP: 
      type: arithmetic
      operator: "+"
      inputVec1: SEL_LEN_REP.outputVec
      inputVec2: 1

    STAT_ASC:
      type: stat
      measure: "mean"
      inputVec: ARI_ASC.outputVec

    STAT_DESC:
      type: stat
      measure: "mean"
      inputVec: ARI_DESC.outputVec

    STAT_REP:
      type: stat
      measure: "mean"
      inputVec: ARI_REP.outputVec
       
  sink:
    f1:
      type: sink
      input: STAT_ASC.outputVec
      label: mean_length_seq_ascending 
      doc:
        type: Real
        length: 1
        description: Mean length of ascending passages.
    f2:
      type: sink
      input: STAT_DESC.outputVec
      label: mean_length_seq_descending
      doc:
        type: Real
        length: 1
        description: Mean length of descending passages.
    f3:
      type: sink
      input: STAT_REP.outputVec
      label: mean_length_seq_repitition
      doc:
        type: Real
        length: 1
        description: Mean length of repetitions.
   