label: Pitch Class Single Features
description: Histogram counts of all 12 PC values (normalized to density), as well as basic circular statistics (cf. `<https://en.wikipedia.org/wiki/Directional_statistics>`_ ).
category: Pitch

feature:

  source:
    PC:
      param: pc
            
  process:

    HIST:
      type: hist
      histogramType: ordinal
      min: 0
      max: 11
      density: True
      inputVec: PC.outputVec

    CIRC_MEAN_ANGLE:
      type: stat 
      measure: circ_mean_angle
      circ_max: 12
      inputVec: PC.outputVec           

    CIRC_MEAN_LENGTH:
      type: stat
      measure: circ_mean_length
      circ_max: 12
      inputVec: PC.outputVec           

    CIRC_VAR:
      type: stat
      measure: circ_var
      circ_max: 12
      inputVec: PC.outputVec           

    CIRC_STD:
      type: stat
      measure: circ_std
      circ_max: 12
      inputVec: PC.outputVec           

    CIRC_DISP:
      type: stat
      measure: circ_disp
      circ_max: 12
      inputVec: PC.outputVec           

    ENTROPY:
      type: stat
      measure: entropy
      numberClasses: 12
      inputVec: PC.outputVec           

  sink:

    F0:
      type: sink
      input: HIST.histVec
      index: 0
      label: pc_hist_density_00_C
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  C
    F1:
      type: sink
      input: HIST.histVec
      index: 1
      label: pc_hist_density_01_C#
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  C#
    F2:
      type: sink
      input: HIST.histVec
      index: 2
      label: pc_hist_density_02_D
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  D
    F3:
      type: sink
      input: HIST.histVec
      index: 3
      label: pc_hist_density_03_Eb
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  Eb
    F4:
      type: sink
      input: HIST.histVec
      index: 4
      label: pc_hist_density_04_E
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  E
    F5:
      type: sink
      input: HIST.histVec
      index: 5
      label: pc_hist_density_05_F
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  F
    F6:
      type: sink
      input: HIST.histVec
      index: 6
      label: pc_hist_density_06_F#
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  F#
    F7:
      type: sink
      input: HIST.histVec
      index: 7
      label: pc_hist_density_07_G
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  G
    F8:
      type: sink
      input: HIST.histVec
      index: 8
      label: pc_hist_density_08_Ab
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  Ab
    F9:
      type: sink
      input: HIST.histVec
      index: 9
      label: pc_hist_density_09_A
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  A
    F10:
      type: sink
      input: HIST.histVec
      index: 10
      label: pc_hist_density_10_Bb
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  Bb
    F11:
      type: sink
      input: HIST.histVec
      index: 11
      label: pc_hist_density_11_B
      doc:
        type: Real
        length: 1
        description: Relative frequency PC =  B

    F12:
      type: sink
      input: CIRC_MEAN_ANGLE.outputVec
      label: pc_circ_mean_angle
      doc:
        type: Real
        length: 1
        description: Angle of circular mean of PC distribution
    F13:
      type: sink
      input: CIRC_MEAN_LENGTH.outputVec
      label: pc_circ_mean_length
      doc:
        type: Real
        length: 1
        description: Length of circular mean of PC distribution
    F14:
      type: sink
      input: CIRC_VAR.outputVec
      label: pc_circ_var
      doc:
        type: Real
        length: 1
        description: Circular variance of PC distribution (=1-length of circular mean)
    F15:
      type: sink
      input: CIRC_STD.outputVec
      label: pc_circ_std
      doc:
        type: Real
        length: 1
        description: Circular standard deviation of PC distribution
    F16:
      type: sink
      input: CIRC_DISP.outputVec
      label: pc_circ_disp
      doc:
        type: Real
        length: 1
        description: Circular dispersion of PC distribution
    F17:
      type: sink
      input: ENTROPY.outputVec
      label: pc_entropy
      doc:
        type: Real
        length: 1
        description: Normalized entropy of PC distribution
      