label: Tonal Diatonic Pitch Class Bigrams
description: "Histogram features for raw MIDI pitch (TDPC) bigrams: all unique TDPC bigrams and all TDPC bigrams occuring at least twice."
category: Sequence/Pitch

feature:

  source:

    TDPC:
      param: tonal-diatonic-pitch-class

  process:

    NGRAM:
      type: ngram
      N: 2
      inputVec: TDPC.outputVec

    NGRAMHIST:
      type: hist
      histogramType: nominal
      inputVec: NGRAM.outputVec

    TH1:
      type: threshold
      inputVec: NGRAMHIST.histVec
      threshold: 1
      operator: "gt"

    SEL1:
      type: selector
      inputVec: NGRAMHIST.bins
      selectVec: TH1.outputVec

    SEL2:
      type: selector
      inputVec: NGRAMHIST.histVec
      selectVec: TH1.outputVec

    ENTROPY:
      type: stat
      measure: entropy_hist
      normalizeEntropy: False
      inputVec: NGRAMHIST.histVec           

    ENTROPY_NORM:
      type: stat
      measure: entropy_hist
      normalizeEntropy: True
      numberClasses: 144
      inputVec: NGRAMHIST.histVec           

  sink:

    F1:
      type: sink
      input: NGRAMHIST.bins
      label: tdpc_bigrams
      doc:
        type: String
        length: Var
        description: Histogram bins (all unique TDPC bigrams)

    F2:
      type: sink
      input: NGRAMHIST.histVec
      label: tdpc_bigram_counts
      doc:
        type: String
        length: Var
        description: Histogram bin counts (all unique TDPC bigrams)

    F3:
      type: sink
      input: SEL1.outputVec
      label: tdpc_bigram_patterns
      doc:
        type: String
        length: Var
        description: Histogram bins (all unique TDPC bigrams occuring at least twice)

    F4:
      type: sink
      input: SEL2.outputVec
      label: tdpc_bigram_pattern_counts
      doc:
        type: Integer
        length: Var
        description: Histogram bin counts (all unique TDPC bigrams occuring at least twice)

    F5:
      type: sink
      input: ENTROPY.outputVec
      label: tdpc_bigram_entropy
      doc:
        type: Real
        length: 1
        description: Unnormalized Entropy of bigram distribution in bits
    F6:
      type: sink
      input: ENTROPY_NORM.outputVec
      label: tdpc_bigram_entropy_norm
      doc:
        type: Real [0,1]
        length: 1
        description: Normalized Entropy of bigram distribution       